FROM rust:latest as dep_cache
ARG image_name
WORKDIR /usr/src/$image_name-tomls
COPY Cargo.toml .
COPY Cargo.lock .
WORKDIR /usr/src/
RUN USER=nobody cargo new --bin $image_name
RUN cp $image_name-tomls/Cargo.* $image_name/
WORKDIR /usr/src/$image_name
RUN cargo build --release
RUN rm target/release/$image_name

FROM dep_cache as builder
ARG image_name
WORKDIR /opt/service
WORKDIR /usr/src/$image_name
COPY . .
RUN cargo build --release
RUN cp /usr/src/$image_name/target/release/$image_name  /opt/service/

FROM ubuntu:bionic as deployment
ARG image_name
WORKDIR /opt/service
COPY --from=1 /opt/service /opt/service
RUN ln -s /opt/service/$image_name /opt/start_service
EXPOSE 8000
ENTRYPOINT [ "/opt/start_service" ]